name: Release
on:
  push:
    tags:
    - "*.*.*"
permissions:
  id-token: write
  contents: write
  checks: write
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.x
    - name: Build and Test
      run: ./Build.ps1
      shell: pwsh
    - name: Report Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results (Linux)
        path: artifacts/**/*.trx
        reporter: dotnet-trx
